[package]
name = "huffman_compression"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
bitvec = "1.0.1"
clap = { version = "4.5.18", features = ["derive"] }
memmap2 = "0.9.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
